<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<NoWarn />
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<Version>1.0.0.0</Version>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<Configurations>Debug;Release</Configurations>
		<LangVersion>latest</LangVersion>
		<NeutralLanguage>en-US</NeutralLanguage>
		<nullable>enable</nullable>
		<License>LICENSE</License>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<WarningsAsErrors />
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<IsPackable>false</IsPackable>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='RELEASE'">
		<Optimize>True</Optimize>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Nano.App" Version="10.0.14" />
	</ItemGroup>

</Project>
