services:
  nanocore.console.minimal:
    image: nanocore.console.minimal
    hostname: nanocore-console-minimal
    restart: on-failure
    build:
      context: ../NanoCore.Console.Minimal
      dockerfile: "Dockerfile.Local"
    env_file:
      - .env
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
